version: "3.5"

services:
  node_app:
    build: ./node_app
    container_name: node_app
    ports:
      - "3000:3000"
    networks:
      - fullStackML
  #
  # flask_app:
  #   build: ./flask_app
  #   container_name: flask_app
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - fullStackML

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - fullStackML
    ports:
      - "27017:27017"


networks:
  fullStackML:
    driver: bridge
